### ISSUE TITLE
Filter by beginning of name only

### ISSUE THREAD

**Issue by SaintNick1214** [TheUltimateC0der/Listrr#134]
I want to create a list of TV shows that start with a letter, like "A".  When I create a filter like this with search in title "A*" it seems to come back with all shows containing the letter A, instead of starting with the letter A.

Any way to tell Listrr to search beginning of title instead of anywhere in title?

**Comment by SaintNick1214** [comment]
Hoping someone has had more luck than I have on this.  I can't for the life of me get Trakt to return results that only start with a letter(s) whether through Listrr or Trakt website

**Comment by TheUltimateC0der** [comment]
@SaintNick1214 That, and a lot of other drawbacks of using the Trakt API lead me to the decision to start to work on listrrv2. 

listrrv2 will more or less make a complete copy of the TMDb database. This will make it easy for me to implement almost any kind of filter the community wants, since I can fire any query against my own database. 

But working on V2 is pretty time consuming. Time that is currently pretty rare for me.

**Comment by SaintNick1214** [comment]
That sounds amazing. Have you made v2 public on github so community can help develop?
________________________________

**Comment by TheUltimateC0der** [comment]
@SaintNick1214 No. V2 is currently not available for the community. V2 is currently only local on my PC. In the past there was no interest for the community to help coding. That's why it's not available currently.

**Comment by TheUltimateC0der** [comment]
This is fixed in V2. Come to the discord linked in the readme, and write me a PM to get access to test it out.
