### ISSUE TITLE
Not working with Trakt anymore?

### ISSUE THREAD

**Issue by TheDemystifier** [TheUltimateC0der/Listrr#140]
I don't use Sonarr, nor Radarr, I'm not a power user. I'm just a simple man who casually checks his filtered lists on Trakt for something to watch. Listrr used to provide this service with some degree of success.

It seems now that there has been an update that stopped creating lists on Trakt directly and now only provide Sonarr and radarr Integration.

Why is it not possible to add filtered lists to Trakt directly like [mdblist.com](https://mdblist.com/)?

UPDATE:
I've only now read this
![image](https://user-images.githubusercontent.com/30221017/196011854-5236a2da-52aa-4295-9276-a52d6264734a.png)
This IMO should be at the homepage. Because I will sadly have to stop using listrr 😔.

**Comment by TheUltimateC0der** [comment]
That change happend yesterday! You can check out the announcement here: https://discord.com/channels/632546249819553812/976243658733002753/1030614687265587220

Ditching trakt.tv has been discussed on the discord (https://discord.com/channels/632546249819553812/1023634964065042563) where no one really seemed to care about that change.

The problem with trakt.tv are the limits that are now in place. You can find out more about the limits here: https://github.com/trakt/api-help/discussions/350. These limits do not reflect what listrr.pro is built for and capable of. It is build to have the freedom to create a list from ANY amount of filters. Therefore, listrr.pro created lists can get HUGE.

Having an external provider where the lists get created on has (on listrr.pro scale) also a negative impact on the external service, and listrr itself. The trakt.tv API had millions of requests from listrr.pro alone. Creating these lists on a external service also adds latency to the list creation. Thats why it takes mdblist so long to populate your list. 

listrr.pro creates a list with thousands of items in the matter of less than 20ms by being able to crush trough multiple GB of data. So with the step of ditching trak.tv, we eliminated both. Not being able to create hunge lists, and the problem of added latency due to calling an external service.


Also I am currently working on similar functionality. So in the near future, you will be able to view your list in the same way you did on trakt. That said, if you liked the functionality from listrr, just wait, there will be updates for the missing features soon.

Also, if you think a feature is missing, do not be shy do discuss them on our discord.

**Comment by TheDemystifier** [comment]
Thank you for your quick reply!

I completely understand. I don't get people who generate lists of 10k+ items as if their lifespan allows them to even watch the trailers of those movies/shows.

Trakt was forced to make a move and so were you. Thank you again, and I hope to see a side-option to add lists (even limited) to Trakt like the old days.

**Comment by TheUltimateC0der** [comment]
> I hope to see a side-option to add lists (even limited) to Trakt like the old days.

Not going to happen. I am creating the functionality that is missing from trakt rather than reimplementing trakt as a list provider. Viewing a list like you could on trakt, is just one feature of many that I will implement.

I am also almost done implementing the list viewing feature. Just check listrr every now and then for new features. And as said, if you are missing something, I generally have no problem implementing it.

**Comment by TheUltimateC0der** [comment]
Now that another user brought up this topic, and I am sending him here to this issue to understand why we ditched trakt.
I implemented the feature to view lists like you could on trakt. You are now also able to Upvote lists.
